"""Переделана модель юзера  для каскадного удаления

Revision ID: 6e412dc81dd8
Revises: 531712db05cd
Create Date: 2026-04-18 17:53:50.286666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e412dc81dd8'
down_revision: Union[str, Sequence[str], None] = '531712db05cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deputies_user_id_key'), 'deputies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('deputies_user_id_key'), 'deputies', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
